### ISSUE TITLE
MODELO DE NEGOCIOS WEB  3.0

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-ggar#1]
[Modelo_ Negocios_Web 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo-ggar/files/9661024/Modelo_.Negocios_Web.3.0.pdf)

**Comment by NoeliaGlez** [comment]
18%

**Comment by mel-16** [comment]
18%Le hace falta tabla de imágenes y solo cuenta con 8 imágenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
